/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;

/**
 *
 * @author 35387
 */
public class ExamEntry extends javax.swing.JFrame {
private Student currentStudent;


    /**
     * Creates new form ExamEntry
     */
    public ExamEntry() {
        initComponents();
        //Database connection code
     
        try {
            Connection conn = DatabaseConnection.getConnection();
            System.out.println("Connected!");
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxModule = new javax.swing.JComboBox<>();
        jTextFieldAssignment1 = new javax.swing.JTextField();
        jTextFieldAssignment2 = new javax.swing.JTextField();
        jTextFieldExam = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInfo = new javax.swing.JTextArea();
        jButtonAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldStudentName = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldAssignment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAssignment1ActionPerformed(evt);
            }
        });

        jTextFieldExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldExamActionPerformed(evt);
            }
        });

        jTextAreaInfo.setEditable(false);
        jTextAreaInfo.setColumns(20);
        jTextAreaInfo.setRows(5);
        jScrollPane1.setViewportView(jTextAreaInfo);

        jButtonAdd.setText("Submit Results");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabel1.setText("Assessment 1");

        jLabel2.setText("Assessment 2");

        jLabel3.setText("Exam");

        jTextFieldStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStudentNameActionPerformed(evt);
            }
        });

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jLabel4.setText("Select Module");

        jToggleButton1.setText("Back");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAssignment2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxModule, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(51, 51, 51)
                                            .addComponent(jTextFieldExam, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(105, 105, 105)
                                            .addComponent(jTextFieldStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jButtonAdd))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldAssignment1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonSearch))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAssignment1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldAssignment2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldExam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(62, 62, 62)
                        .addComponent(jButtonAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAssignment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAssignment1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAssignment1ActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        if (currentStudent == null || currentStudent.getStudent_id() == 0) {
    JOptionPane.showMessageDialog(null, "Please search for and select a student before submitting.");
    return;
}
        
        

        String moduleName = (String) jComboBoxModule.getSelectedItem();
        double assignment_1 = Double.parseDouble(jTextFieldAssignment1.getText());
        double assignment_2 = Double.parseDouble(jTextFieldAssignment2.getText());
        double exam = Double.parseDouble(jTextFieldExam.getText());
        double overall = assignment_1 + assignment_2 + exam;
        
        // Get input from search field
String studentNameInput = jTextFieldStudentName.getText().trim();

// Check if it's empty
if (studentNameInput.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Please enter a student name to search.");
    return;
}
        
        
        
        if (currentStudent.getStudent_id() == 0) {  // Assuming default is 0 if not set
    JOptionPane.showMessageDialog(null, "Please search for and select a student before submitting.");
    return;
}
        
          if (assignment_1 < 0 || assignment_1 > 20) {
    JOptionPane.showMessageDialog(null, "Assignment 1 must be between 0 and 20.");
    return;
}

if (assignment_2 < 0 || assignment_2 > 20) {
    JOptionPane.showMessageDialog(null, "Assignment 2 must be between 0 and 20.");
    return;
}

if (exam < 0 || exam > 60) {
    JOptionPane.showMessageDialog(null, "Exam must be between 0 and 60.");
    return;
}

        // Validation: Ensure the inputs are not empty
        // Proceed to insert the grades into the database
        try {
            // Connect to database
        	Connection conn = DatabaseConnection.getConnection();
                   

            String checkSql = "SELECT * FROM assessment WHERE student_id = ? AND module_name = ?";
            PreparedStatement checkPrest = conn.prepareStatement(checkSql);
            checkPrest.setInt(1, currentStudent.getStudent_id());
            checkPrest.setString(2, moduleName);

            ResultSet checkRs = checkPrest.executeQuery();

            if (checkRs.next()) {
                // Assessment exists --> UPDATE it
                String updateSql = "UPDATE assessment SET assignment_1 = ?, assignment_2 = ?, exam = ?, result = ? "
                        + "WHERE student_id = ? AND module_name = ?";

                PreparedStatement updatePrest = conn.prepareStatement(updateSql);
                updatePrest.setDouble(1, assignment_1);
                updatePrest.setDouble(2, assignment_2);
                updatePrest.setDouble(3, exam);
                updatePrest.setDouble(4, overall);
                updatePrest.setInt(5, currentStudent.getStudent_id());
                updatePrest.setString(6, moduleName);

                updatePrest.executeUpdate();
                JOptionPane.showMessageDialog(null, "Assessment updated successfully for " + currentStudent.getFirst_name());

                updatePrest.close();

            } else {
                // No existing assessment --> INSERT new one
                String insertSql = "INSERT INTO assessment (assignment_1, assignment_2, exam, result, module_name, student_id) "
                        + "VALUES (?, ?, ?, ?, ?, ?)";

                PreparedStatement insertPrest = conn.prepareStatement(insertSql);
                insertPrest.setDouble(1, assignment_1);
                insertPrest.setDouble(2, assignment_2);
                insertPrest.setDouble(3, exam);
                insertPrest.setDouble(4, overall);
                insertPrest.setString(5, moduleName);
                insertPrest.setInt(6, currentStudent.getStudent_id());

                insertPrest.executeUpdate();
                JOptionPane.showMessageDialog(null, "Assessment added successfully for " + currentStudent.getFirst_name());

                insertPrest.close();
            }

            checkRs.close();
            checkPrest.close();
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
           
        }
         jButtonSearchActionPerformed(null);

    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextFieldStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStudentNameActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        currentStudent = new Student(jTextFieldStudentName.getText());

        try {
        	Connection conn = DatabaseConnection.getConnection();


            PreparedStatement prest;

            String sql = "SELECT student.student_id, student.first_name, student.surname, class_group.course_code "
                    + "FROM student "
                    + "INNER JOIN class_group ON student.class_group_code = class_group.class_group_code "
                    + "WHERE student.first_name LIKE ?";

            prest = conn.prepareStatement(sql);
            prest.setString(1, currentStudent.getFirst_name() + "%");
            ResultSet rs = prest.executeQuery();

            String info = "";
            String course_code = "";

            if (rs.next()) {

                currentStudent.setStudent_id(rs.getInt("student_id"));
                currentStudent.setFirst_name(rs.getString("first_name"));
                currentStudent.setSurname(rs.getString("surname"));
                course_code = rs.getString("course_code");

                System.out.println("Course Code: " + course_code);

                info += "ID: " + currentStudent.getStudent_id() + "\n";
                info += "First Name: " + currentStudent.getFirst_name() + "\n";
                info += "Surname: " + currentStudent.getSurname() + "\n";
                info += "Course Code: " + course_code + "\n";
                
                 String marksSql = "SELECT assignment_1, assignment_2, exam FROM assessment WHERE student_id = ?";
            PreparedStatement marksPrest = conn.prepareStatement(marksSql);
            marksPrest.setInt(1, currentStudent.getStudent_id());
            ResultSet marksRs = marksPrest.executeQuery();
             if (marksRs.next()) {
                double assignment1 = marksRs.getDouble("assignment_1");
                double assignment2 = marksRs.getDouble("assignment_2");
                double exam = marksRs.getDouble("exam");

                info += "\nAssignment 1: " + assignment1;
                info += "\nAssignment 2: " + assignment2;
                info += "\nExam: " + exam;
            } else {
                info += "\nNo assessment records found.";
            }
              marksRs.close();
            marksPrest.close();

            

                jTextAreaInfo.setText(info);
            } else {
                JOptionPane.showMessageDialog(null, "No student found");
                jTextAreaInfo.setText("");
                jComboBoxModule.removeAllItems();
            }

            prest.close();
            rs.close();

            if (!course_code.isEmpty()) {
                String moduleSql = "SELECT module_name FROM module WHERE course_code = ?";
                PreparedStatement modulePrest = conn.prepareStatement(moduleSql);
                modulePrest.setString(1, course_code);

                ResultSet moduleRs = modulePrest.executeQuery();

                jComboBoxModule.removeAllItems();

                boolean foundModules = false;
                while (moduleRs.next()) {
                    String module_name = moduleRs.getString("module_name");
                    jComboBoxModule.addItem(module_name);
                    foundModules = true;
                }

                if (!foundModules) {
                    jComboBoxModule.addItem("No modules found");
                }

                modulePrest.close();
                moduleRs.close();
            }

            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTextFieldExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldExamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldExamActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JComboBox<String> jComboBoxModule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaInfo;
    private javax.swing.JTextField jTextFieldAssignment1;
    private javax.swing.JTextField jTextFieldAssignment2;
    private javax.swing.JTextField jTextFieldExam;
    private javax.swing.JTextField jTextFieldStudentName;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
