/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.system;

/**
 *
 * @author 35387
 */
public class options extends javax.swing.JFrame {

    /**
     * Creates new form options
     */
    public options() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSearch = new javax.swing.JLabel();
        jButtonStaffSearch = new javax.swing.JButton();
        jButtonStudentSearch = new javax.swing.JButton();
        jLabelUpdate = new javax.swing.JLabel();
        jButtonStaffUpdate = new javax.swing.JButton();
        jButtonStudentUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelGrade = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelSearch.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSearch.setText("Search...");

        jButtonStaffSearch.setText("Staff Search");
        jButtonStaffSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStaffSearchActionPerformed(evt);
            }
        });

        jButtonStudentSearch.setText("Student Search");
        jButtonStudentSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStudentSearchActionPerformed(evt);
            }
        });

        jLabelUpdate.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelUpdate.setText("Update...");

        jButtonStaffUpdate.setText("Staff Update");
        jButtonStaffUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStaffUpdateActionPerformed(evt);
            }
        });

        jButtonStudentUpdate.setText("Student Update");
        jButtonStudentUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStudentUpdateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Swis721 BlkCn BT", 1, 36)); // NOI18N
        jLabel1.setText("GTI Exam Entry System");

        jLabelGrade.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelGrade.setText("Grade...");

        jButton1.setText("Grade Students");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jButtonStaffUpdate)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonStudentUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabelUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jButtonStaffSearch)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonStudentSearch))
                                .addComponent(jLabelGrade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(96, 96, 96)
                .addComponent(jLabelSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStaffSearch)
                    .addComponent(jButtonStudentSearch))
                .addGap(41, 41, 41)
                .addComponent(jLabelUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStaffUpdate)
                    .addComponent(jButtonStudentUpdate))
                .addGap(43, 43, 43)
                .addComponent(jLabelGrade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStaffSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStaffSearchActionPerformed
        StaffSearchFrame f0 = new StaffSearchFrame();
        f0.setVisible(true);
    }//GEN-LAST:event_jButtonStaffSearchActionPerformed

    private void jButtonStudentSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStudentSearchActionPerformed
        studentSearchFrame f0 = new studentSearchFrame();
        f0.setVisible(true);
    }//GEN-LAST:event_jButtonStudentSearchActionPerformed

    private void jButtonStaffUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStaffUpdateActionPerformed
        staffUpdate f0 = new staffUpdate();
        f0.setVisible(true);
    }//GEN-LAST:event_jButtonStaffUpdateActionPerformed

    private void jButtonStudentUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStudentUpdateActionPerformed
        studentUpdate f0 = new studentUpdate();
        f0.setVisible(true);
    }//GEN-LAST:event_jButtonStudentUpdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ExamEntry f0 = new ExamEntry();
        f0.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new options().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonStaffSearch;
    private javax.swing.JButton jButtonStaffUpdate;
    private javax.swing.JButton jButtonStudentSearch;
    private javax.swing.JButton jButtonStudentUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelGrade;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelUpdate;
    // End of variables declaration//GEN-END:variables
}
