/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;


/**
 *
 * @author 35387
 */
public class StaffSearchFrame extends javax.swing.JFrame {

    /**
     * Creates new form staffFrame
     */
    public StaffSearchFrame() {
        initComponents();
        
        try {
            Connection conn = DatabaseConnection.getConnection();
            System.out.println("Connected!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelStaffSearch = new javax.swing.JLabel();
        jScrollPaneInformation = new javax.swing.JScrollPane();
        jTextAreaInfo = new javax.swing.JTextArea();
        jTextFieldStaffName = new javax.swing.JTextField();
        jLabelStaffName = new javax.swing.JLabel();
        jLabelinfo = new javax.swing.JLabel();
        jButtonSearch = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelStaffSearch.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelStaffSearch.setText("Staff Search");

        jTextAreaInfo.setEditable(false);
        jTextAreaInfo.setColumns(20);
        jTextAreaInfo.setRows(5);
        jScrollPaneInformation.setViewportView(jTextAreaInfo);

        jTextFieldStaffName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStaffNameActionPerformed(evt);
            }
        });

        jLabelStaffName.setText("Staff Name");

        jLabelinfo.setText("Information on Staff Member");

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelStaffSearch)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStaffName)
                            .addComponent(jButtonSearch)
                            .addComponent(backButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelinfo))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelStaffSearch)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelinfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabelStaffName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSearch)
                        .addGap(51, 51, 51)
                        .addComponent(backButton)
                        .addGap(43, 43, 43))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
         Staff s = new Staff(jTextFieldStaffName.getText());

        

        try {
           // Class.forName(driver).newInstance();
        	Connection conn = DatabaseConnection.getConnection();

             PreparedStatement prest;

            String sql = "SELECT * FROM staff WHERE first_name LIKE  ?";
            prest = conn.prepareStatement(sql);
            prest.setString(1, s.getFirst_name()+"%" );
            ResultSet rs = prest.executeQuery();

            String info = "";
            while (rs.next()) {
                System.out.println("");
                s.setStaff_id(rs.getInt(1));
                s.setFirst_name(rs.getString(2));
                s.setSurname(rs.getString(3));
                s.setAddress_line1(rs.getString(4));
                s.setAddress_line2(rs.getString(5));
                s.setCounty(rs.getString(6));
                s.setEircode(rs.getString(7));
                s.setEmail(rs.getString(8));
                s.setPhone_number(rs.getString(9));
                s.setDate_of_birth(rs.getString(10));
                s.setPPSN(rs.getString(11));
                info += "Staff ID" +s.getStaff_id() + "\nFirst Name: "+s.getFirst_name()+"\nSurname: "+s.getSurname()
                        +"\nAddress Line 1: " + s.getAddress_line1()+"\nAddress Line 2: " + s.getAddress_line2() +"\nCounty: "+s.getCounty()
                        + "\nEircode: " + s.getEircode() + "\nEmail: " + s.getEmail() + "\nPhone Number: " + s.getPhone_number()
                        +"\nDate of Birth: " + s.getDate_of_birth() + "\nPPSN" + s.getPPSN();
                
            }
            prest.close();
            rs.close();
            conn.close();
            jTextAreaInfo.setText(info);
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTextFieldStaffNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStaffNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStaffNameActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffSearchFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabelStaffName;
    private javax.swing.JLabel jLabelStaffSearch;
    private javax.swing.JLabel jLabelinfo;
    private javax.swing.JScrollPane jScrollPaneInformation;
    private javax.swing.JTextArea jTextAreaInfo;
    private javax.swing.JTextField jTextFieldStaffName;
    // End of variables declaration//GEN-END:variables
}
