/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;

/**
 *
 * @author 35387
 */
public class staffUpdate extends javax.swing.JFrame {



    /**
     * Creates new form staffUpdate
     */
    public staffUpdate() {
        initComponents();
        
        try {
            Connection conn = DatabaseConnection.getConnection();
            System.out.println("Connected!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldStaffName = new javax.swing.JTextField();
        jLabelStaffName = new javax.swing.JLabel();
        jButtonSearch = new javax.swing.JButton();
        jLabelStaffID = new javax.swing.JLabel();
        jLabelFirstName = new javax.swing.JLabel();
        jLabelSurname = new javax.swing.JLabel();
        jLabelAddressLine1 = new javax.swing.JLabel();
        jLabelAddressLine2 = new javax.swing.JLabel();
        jLabelCounty = new javax.swing.JLabel();
        jLabelEircode = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPhoneNumber = new javax.swing.JLabel();
        jLabelDateOfBirth = new javax.swing.JLabel();
        jLabelPPSN = new javax.swing.JLabel();
        jButtonUpdate = new javax.swing.JButton();
        jTextFieldStaffID = new javax.swing.JTextField();
        jTextFieldFirstName = new javax.swing.JTextField();
        jTextFieldSurname = new javax.swing.JTextField();
        jTextFieldAddressLine1 = new javax.swing.JTextField();
        jTextFieldAddressLine2 = new javax.swing.JTextField();
        jTextFieldCounty = new javax.swing.JTextField();
        jTextFieldEircode = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jTextFieldDateOfBirth = new javax.swing.JTextField();
        jTextFieldPPSN = new javax.swing.JTextField();
        jButtonDelete = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelStaffName.setText("Staff Name");

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jLabelStaffID.setText("Staff ID");

        jLabelFirstName.setText("First Name");

        jLabelSurname.setText("Surname");

        jLabelAddressLine1.setText("Address Line 1");

        jLabelAddressLine2.setText("Address Line 2");

        jLabelCounty.setText("County");

        jLabelEircode.setText("Eircode");

        jLabelEmail.setText("Email");

        jLabelPhoneNumber.setText("Phone Number");

        jLabelDateOfBirth.setText("Date of Birth");

        jLabelPPSN.setText("PPSN");

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelStaffName)
                        .addGap(36, 36, 36)
                        .addComponent(jTextFieldStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelPPSN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCounty, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelSurname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelEircode, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelStaffID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabelAddressLine1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelAddressLine2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabelPhoneNumber)))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldStaffID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSurname)
                            .addComponent(jTextFieldAddressLine1)
                            .addComponent(jTextFieldAddressLine2)
                            .addComponent(jTextFieldCounty)
                            .addComponent(jTextFieldEircode)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jTextFieldPhoneNumber)
                            .addComponent(jTextFieldDateOfBirth)
                            .addComponent(jTextFieldPPSN))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSearch)
                        .addGap(102, 102, 102))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonBack)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonAdd)
                                .addComponent(jButtonDelete)
                                .addComponent(jButtonUpdate)))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStaffName)
                    .addComponent(jButtonSearch))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStaffID)
                            .addComponent(jTextFieldStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFirstName)
                            .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSurname)
                            .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButtonAdd)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDelete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddressLine1)
                    .addComponent(jTextFieldAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddressLine2)
                    .addComponent(jTextFieldAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCounty)
                    .addComponent(jTextFieldCounty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEircode)
                    .addComponent(jTextFieldEircode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhoneNumber)
                    .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBack))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDateOfBirth)
                    .addComponent(jTextFieldDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPPSN)
                    .addComponent(jTextFieldPPSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        Staff s = new Staff(jTextFieldStaffName.getText());
        
        try {
            // Class.forName(driver).newInstance();
        	Connection conn = DatabaseConnection.getConnection();

            PreparedStatement prest;

            String sql = "SELECT * FROM staff WHERE first_name LIKE  ?";

            prest = conn.prepareStatement(sql);
            prest.setString(1, s.getFirst_name() + "%");

            ResultSet rs = prest.executeQuery();

            String info = "";
            while (rs.next()) {
                System.out.println("");
                s.setStaff_id(rs.getInt(1));
                s.setFirst_name(rs.getString(2));
                s.setSurname(rs.getString(3));
                s.setAddress_line1(rs.getString(4));
                s.setAddress_line2(rs.getString(5));
                s.setCounty(rs.getString(6));
                s.setEircode(rs.getString(7));
                s.setEmail(rs.getString(8));
                s.setPhone_number(rs.getString(9));
                s.setDate_of_birth(rs.getString(10));
                s.setPPSN(rs.getString(11));
                jTextFieldStaffID.setText(Integer.toString(s.getStaff_id()));
                jTextFieldFirstName.setText(s.getFirst_name());
                jTextFieldSurname.setText(s.getSurname());
                jTextFieldAddressLine1.setText(s.getAddress_line1());
                jTextFieldAddressLine2.setText(s.getAddress_line2());
                jTextFieldCounty.setText(s.getCounty());
                jTextFieldEircode.setText(s.getEircode());
                jTextFieldEmail.setText(s.getEmail());
                jTextFieldPhoneNumber.setText(s.getPhone_number());
                jTextFieldDateOfBirth.setText(s.getDate_of_birth());
                jTextFieldPPSN.setText(s.getPPSN());

            }
            prest.close();
            rs.close();
            conn.close();

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
         Staff s = new Staff(jTextFieldStaffName.getText());

    s.setStaff_id(Integer.parseInt(jTextFieldStaffID.getText()));
    s.setFirst_name(jTextFieldFirstName.getText());
    s.setSurname(jTextFieldSurname.getText());
    s.setAddress_line1(jTextFieldAddressLine1.getText());
    s.setAddress_line2(jTextFieldAddressLine2.getText());
    s.setCounty(jTextFieldCounty.getText());
    s.setEircode(jTextFieldEircode.getText());
    s.setEmail(jTextFieldEmail.getText());
    s.setPhone_number(jTextFieldPhoneNumber.getText());
    s.setDate_of_birth(jTextFieldDateOfBirth.getText());
    s.setPPSN(jTextFieldPPSN.getText());

    try {
    	Connection conn = DatabaseConnection.getConnection();

        String sql = "UPDATE staff SET first_name=?, surname=?, address_line1=?, "
                   + "address_line2=?, county=?, eircode=?, email=?, phone_number=?, "
                   + "date_of_birth=?, ppsn=? WHERE staff_id=?";

        PreparedStatement prest = conn.prepareStatement(sql);
        prest.setString(1, s.getFirst_name());
        prest.setString(2, s.getSurname());
        prest.setString(3, s.getAddress_line1());
        prest.setString(4, s.getAddress_line2()); 
        prest.setString(5, s.getCounty());
        prest.setString(6, s.getEircode());
        prest.setString(7, s.getEmail());
        prest.setString(8, s.getPhone_number());
        prest.setString(9, s.getDate_of_birth());
        prest.setString(10, s.getPPSN());
        prest.setInt(11, s.getStaff_id()); 

        prest.executeUpdate();

        prest.close();
        conn.close();
        System.out.println("Staff updated successfully.");

    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
        
    
        }
        
        
        
        
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        Staff s = new Staff(jTextFieldStaffName.getText());
        
        s.setStaff_id(Integer.parseInt(jTextFieldStaffID.getText()));
        s.setFirst_name(jTextFieldFirstName.getText());
        
          int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete " + s.getFirst_name()+ " from "
                + "your records");

        if (confirm == 0) {
            System.out.println("confirming delete");
             try {
            
            	 Connection conn = DatabaseConnection.getConnection();

            PreparedStatement prest;

            String sql = "DELETE FROM staff WHERE staff_id= ?";
                    

            prest = conn.prepareStatement(sql);
            prest.setInt(1, s.getStaff_id());
            
            int del = prest.executeUpdate();
                System.out.println("Number of deleted records: " + del);                
                conn.close();

           

            
            
            prest.close();
            
            conn.close();

        } catch (Exception e) {
            System.out.println(e);
        }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
         Staff s = new Staff(jTextFieldStaffName.getText());
        s.setStaff_id(Integer.parseInt(jTextFieldStaffID.getText()));
        s.setFirst_name(jTextFieldFirstName.getText());
        s.setSurname(jTextFieldSurname.getText());
        s.setAddress_line1(jTextFieldAddressLine1.getText());
        s.setAddress_line2(jTextFieldAddressLine2.getText());
        s.setCounty(jTextFieldCounty.getText());
        s.setEircode(jTextFieldEircode.getText());
        s.setEmail(jTextFieldEmail.getText());
        s.setPhone_number(jTextFieldPhoneNumber.getText());
        s.setDate_of_birth(jTextFieldDateOfBirth.getText());
        s.setPPSN(jTextFieldPPSN.getText());
       
        
         try {
            
        	 Connection conn = DatabaseConnection.getConnection();

            PreparedStatement prest;

            String sql= "INSERT INTO staff " +
"                           (staff_id,first_name,surname,address_line1,address_line2,county,eircode,email,phone_number,date_of_birth,ppsn)" +
"                           VALUES (?,?,?,?,?,?,?,?,?,?,?)";
                    

            prest = conn.prepareStatement(sql);
            
            prest.setInt(1, s.getStaff_id());
            prest.setString(2, s.getFirst_name());
            prest.setString(3, s.getSurname());
            prest.setString(4, s.getAddress_line1());
            prest.setString(5, s.getAddress_line2());
            prest.setString(6, s.getCounty());
            prest.setString(7, s.getEircode());
            prest.setString(8, s.getEmail());
            prest.setString(9, s.getPhone_number());
            prest.setString(10, s.getDate_of_birth());
            prest.setString(11, s.getPPSN());
          


                 prest.executeUpdate();
                 
                  JOptionPane.showMessageDialog(null, "A new staff member, "+s.getFirst_name()+ ""
                    + ", has been added to the database" );
            conn.close();
            prest.close();

            
            prest.close();
     
            conn.close();

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staffUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staffUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staffUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staffUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staffUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelAddressLine1;
    private javax.swing.JLabel jLabelAddressLine2;
    private javax.swing.JLabel jLabelCounty;
    private javax.swing.JLabel jLabelDateOfBirth;
    private javax.swing.JLabel jLabelEircode;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelPPSN;
    private javax.swing.JLabel jLabelPhoneNumber;
    private javax.swing.JLabel jLabelStaffID;
    private javax.swing.JLabel jLabelStaffName;
    private javax.swing.JLabel jLabelSurname;
    private javax.swing.JTextField jTextFieldAddressLine1;
    private javax.swing.JTextField jTextFieldAddressLine2;
    private javax.swing.JTextField jTextFieldCounty;
    private javax.swing.JTextField jTextFieldDateOfBirth;
    private javax.swing.JTextField jTextFieldEircode;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldPPSN;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JTextField jTextFieldStaffID;
    private javax.swing.JTextField jTextFieldStaffName;
    private javax.swing.JTextField jTextFieldSurname;
    // End of variables declaration//GEN-END:variables
}
