/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.system;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;


/**
 *
 * @author 35387
 */
public class studentUpdate extends javax.swing.JFrame {
    
     

    /**
     * Creates new form studentUpdate
     */
    public studentUpdate() {
        initComponents();
        loadClassGroupCodes();
        
        try {
            Connection conn = DatabaseConnection.getConnection();
            System.out.println("Connected!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldFirstName = new javax.swing.JTextField();
        jTextFieldSurname = new javax.swing.JTextField();
        jTextFieldAddressLine1 = new javax.swing.JTextField();
        jTextFieldAddressLine2 = new javax.swing.JTextField();
        jTextFieldCounty = new javax.swing.JTextField();
        jTextFieldEircode = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jTextFieldDateOfBirth = new javax.swing.JTextField();
        jTextFieldPPSN = new javax.swing.JTextField();
        jLabelFirstName = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();
        jLabelSurname = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jLabelAddressLine1 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jLabelAddressLine2 = new javax.swing.JLabel();
        jLabelCounty = new javax.swing.JLabel();
        jLabelEircode = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPhoneNumber = new javax.swing.JLabel();
        jLabelDateOfBirth = new javax.swing.JLabel();
        jLabelPPSN = new javax.swing.JLabel();
        jTextFieldStudentName = new javax.swing.JTextField();
        jLabelStudentName = new javax.swing.JLabel();
        jButtonSearch = new javax.swing.JButton();
        jLabelStudentID = new javax.swing.JLabel();
        jButtonUpdate = new javax.swing.JButton();
        jTextFieldStudentID = new javax.swing.JTextField();
        jComboBoxClassCode = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelFirstName.setText("First Name");

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabelSurname.setText("Surname");

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabelAddressLine1.setText("Address Line 1");

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabelAddressLine2.setText("Address Line 2");

        jLabelCounty.setText("County");

        jLabelEircode.setText("Eircode");

        jLabelEmail.setText("Email");

        jLabelPhoneNumber.setText("Phone Number");

        jLabelDateOfBirth.setText("Date of Birth");

        jLabelPPSN.setText("PPSN");

        jLabelStudentName.setText("Student Name");

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jLabelStudentID.setText("Student ID");

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jComboBoxClassCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PSD", "ASD" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelStudentName)
                        .addGap(36, 36, 36)
                        .addComponent(jTextFieldStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelPPSN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCounty, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelSurname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelEircode, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelStudentID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelAddressLine1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelAddressLine2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabelPhoneNumber)))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxClassCode, 0, 180, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldStudentID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldSurname)
                                .addComponent(jTextFieldAddressLine1)
                                .addComponent(jTextFieldAddressLine2)
                                .addComponent(jTextFieldCounty)
                                .addComponent(jTextFieldEircode)
                                .addComponent(jTextFieldEmail)
                                .addComponent(jTextFieldPhoneNumber)
                                .addComponent(jTextFieldDateOfBirth)
                                .addComponent(jTextFieldPPSN)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSearch)
                        .addGap(102, 102, 102))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonBack)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonAdd)
                                .addComponent(jButtonDelete)
                                .addComponent(jButtonUpdate)))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStudentName)
                    .addComponent(jButtonSearch))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStudentID)
                            .addComponent(jTextFieldStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFirstName)
                            .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSurname)
                            .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButtonAdd)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDelete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddressLine1)
                    .addComponent(jTextFieldAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddressLine2)
                    .addComponent(jTextFieldAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCounty)
                    .addComponent(jTextFieldCounty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEircode)
                    .addComponent(jTextFieldEircode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhoneNumber)
                    .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBack))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDateOfBirth)
                    .addComponent(jTextFieldDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPPSN)
                    .addComponent(jTextFieldPPSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxClassCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        Student st = new Student(jTextFieldStudentName.getText());

        st.setStudent_id(Integer.parseInt(jTextFieldStudentID.getText()));
        st.setFirst_name(jTextFieldFirstName.getText());

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete " + st.getFirst_name()+ " from "
            + "your records");

        if (confirm == 0) {
            System.out.println("confirming delete");
            try {

            	Connection conn = DatabaseConnection.getConnection();

                PreparedStatement prest;

                String sql = "DELETE FROM student WHERE student_id= ?";

                prest = conn.prepareStatement(sql);
                prest.setInt(1, st.getStudent_id());

                int del = prest.executeUpdate();
                System.out.println("Number of deleted records: " + del);
                conn.close();

                prest.close();

                conn.close();

            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        Student st = new Student(jTextFieldStudentName.getText());
        st.setStudent_id(Integer.parseInt(jTextFieldStudentID.getText()));
        st.setFirst_name(jTextFieldFirstName.getText());
        st.setSurname(jTextFieldSurname.getText());
        st.setAddress_line1(jTextFieldAddressLine1.getText());
        st.setAddress_line2(jTextFieldAddressLine2.getText());
        st.setCounty(jTextFieldCounty.getText());
        st.setEircode(jTextFieldEircode.getText());
        st.setEmail(jTextFieldEmail.getText());
        st.setPhone_number(jTextFieldPhoneNumber.getText());
        st.setDate_of_birth(jTextFieldDateOfBirth.getText());
        st.setPPSN(jTextFieldPPSN.getText());
        st.setClass_group_code(((String) jComboBoxClassCode.getSelectedItem()).trim().toUpperCase());

        try {

        	Connection conn = DatabaseConnection.getConnection();

            PreparedStatement prest;

            String sql= "INSERT INTO student " +
            "                           (student_id,first_name,surname,address_line1,address_line2,county,eircode,email,phone_number,date_of_birth,ppsn,class_group_code)" +
            "                           VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";

            prest = conn.prepareStatement(sql);

            prest.setInt(1, st.getStudent_id());
            prest.setString(2, st.getFirst_name());
            prest.setString(3, st.getSurname());
            prest.setString(4, st.getAddress_line1());
            prest.setString(5, st.getAddress_line2());
            prest.setString(6, st.getCounty());
            prest.setString(7, st.getEircode());
            prest.setString(8, st.getEmail());
            prest.setString(9,st.getPhone_number());
            prest.setString(10, st.getDate_of_birth());
            prest.setString(11, st.getPPSN());
            prest.setString(12, st.getClass_group_code());
            

            prest.executeUpdate();

            JOptionPane.showMessageDialog(null, "A new student, "+st.getFirst_name()+ ""
                + ", has been added to the database" );
            conn.close();
            prest.close();

            prest.close();

            conn.close();

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        Student st = new Student(jTextFieldStudentName.getText());

        try {
        	
        	Connection conn = DatabaseConnection.getConnection();

            PreparedStatement prest;

            String sql = "SELECT * FROM student WHERE first_name LIKE  ?";

            prest = conn.prepareStatement(sql);
            prest.setString(1, st.getFirst_name() + "%");

            ResultSet rs = prest.executeQuery();

            String info = "";
            while (rs.next()) {
                System.out.println("");
                st.setStudent_id(rs.getInt(1));
                st.setClass_group_code(rs.getString(2));
                st.setFirst_name(rs.getString(3));
                st.setSurname(rs.getString(4));
                st.setAddress_line1(rs.getString(5));
                st.setAddress_line2(rs.getString(6));
                st.setCounty(rs.getString(7));
                st.setEircode(rs.getString(8));
                st.setEmail(rs.getString(9));
                st.setPhone_number(rs.getString(10));
                st.setDate_of_birth(rs.getString(11));
                st.setPPSN(rs.getString(12));
                
                jTextFieldStudentID.setText(Integer.toString(st.getStudent_id()));
                jTextFieldFirstName.setText(st.getFirst_name());
                jTextFieldSurname.setText(st.getSurname());
                jTextFieldAddressLine1.setText(st.getAddress_line1());
                jTextFieldAddressLine2.setText(st.getAddress_line2());
                jTextFieldCounty.setText(st.getCounty());
                jTextFieldEircode.setText(st.getEircode());
                jTextFieldEmail.setText(st.getEmail());
                jTextFieldPhoneNumber.setText(st.getPhone_number());
                jTextFieldDateOfBirth.setText(st.getDate_of_birth());
                jTextFieldPPSN.setText(st.getPPSN());
                jComboBoxClassCode.setSelectedItem(st.getClass_group_code());

            }
            prest.close();
            rs.close();
            conn.close();

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        Student st = new Student(jTextFieldStudentName.getText());

        st.setStudent_id(Integer.parseInt(jTextFieldStudentID.getText()));
        st.setFirst_name(jTextFieldFirstName.getText());
        st.setSurname(jTextFieldSurname.getText());
        st.setAddress_line1(jTextFieldAddressLine1.getText());
        st.setAddress_line2(jTextFieldAddressLine2.getText());
        st.setCounty(jTextFieldCounty.getText());
        st.setEircode(jTextFieldEircode.getText());
        st.setEmail(jTextFieldEmail.getText());
        st.setPhone_number(jTextFieldPhoneNumber.getText());
        st.setDate_of_birth(jTextFieldDateOfBirth.getText());
        st.setPPSN(jTextFieldPPSN.getText());
        st.setClass_group_code(((String) jComboBoxClassCode.getSelectedItem()).trim());

        try {

        	Connection conn = DatabaseConnection.getConnection();

            PreparedStatement prest;

            String sql= "UPDATE student SET first_name=?, "
            + "surname=?,address_line1=?,"
            + "address_line2=?, county=?,eircode=?,"
            + "email=?,phone_number=?,date_of_birth=?,ppsn=?, class_group_code=? "
            + "WHERE student_id=? ";

            prest = conn.prepareStatement(sql);
            

            prest.setString(1, st.getFirst_name());
            prest.setString(2,st.getSurname());
            prest.setString(3, st.getAddress_line1());
            prest.setString(4, st.getAddress_line2());
            prest.setString(5, st.getCounty());
            prest.setString(6, st.getEircode());
            prest.setString(7, st.getEmail());
            prest.setString(8, st.getPhone_number());
            prest.setString(9, st.getDate_of_birth());
            prest.setString(10, st.getPPSN());
            prest.setString(11, st.getClass_group_code());
            prest.setInt(12, st.getStudent_id());
            

            prest.executeUpdate();

            prest.close();

            conn.close();

        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_jButtonUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentUpdate().setVisible(true);
            }
        });
    }private void loadClassGroupCodes() {
    try {
        System.out.println("Loading Class Group Codes...");
        Connection conn = DatabaseConnection.getConnection();

        String sql = "SELECT class_group_code FROM class_group";
        PreparedStatement prest = conn.prepareStatement(sql);
        ResultSet rs = prest.executeQuery();

        jComboBoxClassCode.removeAllItems(); // Clear existing items

        while (rs.next()) {
            String classCode = rs.getString("class_group_code");
            jComboBoxClassCode.addItem(classCode); // Add each class group code
        }

        rs.close();
        prest.close();
        conn.close();
    } catch (Exception e) {
        System.out.println("Error loading class group codes: " + e);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxClassCode;
    private javax.swing.JLabel jLabelAddressLine1;
    private javax.swing.JLabel jLabelAddressLine2;
    private javax.swing.JLabel jLabelCounty;
    private javax.swing.JLabel jLabelDateOfBirth;
    private javax.swing.JLabel jLabelEircode;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelPPSN;
    private javax.swing.JLabel jLabelPhoneNumber;
    private javax.swing.JLabel jLabelStudentID;
    private javax.swing.JLabel jLabelStudentName;
    private javax.swing.JLabel jLabelSurname;
    private javax.swing.JTextField jTextFieldAddressLine1;
    private javax.swing.JTextField jTextFieldAddressLine2;
    private javax.swing.JTextField jTextFieldCounty;
    private javax.swing.JTextField jTextFieldDateOfBirth;
    private javax.swing.JTextField jTextFieldEircode;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldPPSN;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JTextField jTextFieldStudentID;
    private javax.swing.JTextField jTextFieldStudentName;
    private javax.swing.JTextField jTextFieldSurname;
    // End of variables declaration//GEN-END:variables
}
